#!/usr/bin/env python3
"""Export the trip's saved places to CSV + KML for Google My Maps import.

Reads tripdata.js (generated by build_tripdata.py) so the export always
matches what the site shows.
"""
import csv
import json
import os
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))

raw = open(os.path.join(HERE, "tripdata.js")).read()
trip = json.loads(raw[raw.index("{"): raw.rindex("}") + 1])

rows = []  # (folder, name, desc, lat, lng)

for g in trip.get("poiGroups", []):
    for p in g.get("pois", []):
        if not (p.get("lat") and p.get("lng")):
            continue
        desc = p.get("description", "")
        extra = []
        if p.get("detour") and p["detour"] != "on route":
            extra.append("Detour: " + p["detour"])
        if p.get("nearStop"):
            extra.append("Near: " + p["nearStop"])
        if extra:
            desc += " [" + " | ".join(extra) + "]"
        rows.append(("Nature & sights", p["name"], desc, p["lat"], p["lng"]))

for t in trip.get("towns", []):
    for f in t.get("food", []):
        if not (f.get("lat") and f.get("lng")):
            continue
        desc = f.get("description", "")
        if f.get("price"):
            desc += " [" + f["price"] + "]"
        folder = "Resupply (groceries)" if f.get("type") == "grocery" else "Eat & drink"
        rows.append((folder, f["name"], (f.get("type", "") + ": " + desc).strip(": "), f["lat"], f["lng"]))
    for s in t.get("sleep", []):
        if not (s.get("lat") and s.get("lng")):
            continue
        desc = s.get("description", "")
        bits = [b for b in (s.get("price"), s.get("bookingNote")) if b]
        if bits:
            desc += " [" + " | ".join(bits) + "]"
        rows.append(("Sleep", s["name"], (s.get("type", "") + ": " + desc).strip(": "), s["lat"], s["lng"]))

# de-duplicate by (name, rounded coords)
seen, unique = set(), []
for r in rows:
    key = (r[1].lower(), round(r[3], 3), round(r[4], 3))
    if key in seen:
        continue
    seen.add(key)
    unique.append(r)

csv_path = os.path.join(HERE, "saved_places.csv")
with open(csv_path, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Name", "Category", "Description", "Latitude", "Longitude"])
    for folder, name, desc, lat, lng in unique:
        w.writerow([name, folder, desc, lat, lng])

kml_path = os.path.join(HERE, "saved_places.kml")
folders = {}
for folder, name, desc, lat, lng in unique:
    folders.setdefault(folder, []).append((name, desc, lat, lng))

STYLE = {
    "Nature & sights": "http://maps.google.com/mapfiles/kml/paddle/grn-circle.png",
    "Eat & drink": "http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png",
    "Resupply (groceries)": "http://maps.google.com/mapfiles/kml/paddle/wht-circle.png",
    "Sleep": "http://maps.google.com/mapfiles/kml/paddle/blu-circle.png",
}
with open(kml_path, "w") as f:
    f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    f.write('<kml xmlns="http://www.opengis.net/kml/2.2"><Document>\n')
    f.write("<name>Røros→Flåm bikepacking · saved places</name>\n")
    for i, (folder, items) in enumerate(folders.items()):
        f.write(f'<Style id="s{i}"><IconStyle><Icon><href>{STYLE.get(folder, "")}</href></Icon></IconStyle></Style>\n')
    for i, (folder, items) in enumerate(folders.items()):
        f.write(f"<Folder><name>{escape(folder)}</name>\n")
        for name, desc, lat, lng in items:
            f.write("<Placemark>")
            f.write(f"<name>{escape(name)}</name>")
            f.write(f"<description>{escape(desc)}</description>")
            f.write(f"<styleUrl>#s{i}</styleUrl>")
            f.write(f"<Point><coordinates>{lng},{lat},0</coordinates></Point>")
            f.write("</Placemark>\n")
        f.write("</Folder>\n")

    f.write('<Style id="route"><LineStyle><color>ff1f35c8</color><width>3</width></LineStyle></Style>\n')
    f.write("<Folder><name>Route</name>\n")
    coords = " ".join(f"{p[1]},{p[0]},0" for p in trip.get("track", []))
    f.write(f"<Placemark><name>Røros→Flåm (RWGPS 41496641)</name><styleUrl>#route</styleUrl>"
            f"<LineString><tessellate>1</tessellate><coordinates>{coords}</coordinates></LineString></Placemark>\n")
    spur = " ".join(f"{p[1]},{p[0]},0" for p in trip.get("besseggenSpur", []))
    if spur:
        f.write(f"<Placemark><name>Besseggen detour (Fv51 over Valdresflye, approx)</name><styleUrl>#route</styleUrl>"
                f"<LineString><tessellate>1</tessellate><coordinates>{spur}</coordinates></LineString></Placemark>\n")
    f.write("</Folder>\n")
    f.write("</Document></kml>\n")

print(f"wrote {csv_path} and {kml_path}: {len(unique)} places in {len(folders)} folders")
for folder, items in folders.items():
    print(f"  {folder}: {len(items)}")
